apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: moniroting-CRDs-multicluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
                # - staging
                # - prod
  template:
    metadata:
      name: monitoring-CRDs-{{name}}
    spec:
      project: monitoring
      source:
        repoURL: git@github.com:erickmpene/monitoring.git
        targetRevision: main
        path: CRDs-for-moniroting/envs/{{name}}
        directory:
          recurse: true
      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
