apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-multicluster
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
                # - staging
                # - prod
  template:
    metadata:
      name: monitoring-{{name}}
    spec:
      project: monitoring
      source:
        repoURL: git@github.com:erickmpene/monitoring.git
        targetRevision: main
        path: kube-prometheus-stack/envs/{{name}}
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
