apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crds-multicluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
    - clusters:
        selector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
                # - staging
                # - prod
  template:
    metadata:
      name: monitoring-crds-{{name}}
    spec:
      project: monitoring
      source:
        repoURL: git@github.com:erickmpene/monitoring.git
        targetRevision: main
        path: crds-for-monitoring/{{name}}
        directory:
          recurse: true
      destination:
        server: '{{server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
